modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT"
[[mods]]
modId = "creon"
version = "${file.jarVersion}"
displayName = "Creon"
#updateJSONURL="http://myurl.me/"
displayURL="https://github.com/ElytraServers/CreonMod"
logoFile="creon.png"
credits="Inspired by HGLMiddle."
authors = "Taskeren"

description = '''
Creon is a prescription medicine used to treat people who cannot digest food normally.
'''

[[dependencies.creon]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"
